import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
    ArrowRight, ArrowLeft, Download, Copy, CheckCircle2, 
    AlertTriangle, Info, Loader2, Server, Network, Shield, Terminal, Zap
} from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { toast } from 'sonner';

export default function RPCSetupWizard({ onComplete, initialConfig = {} }) {
    const [step, setStep] = useState(1);
    const [config, setConfig] = useState({
        rpcuser: initialConfig.username || '',
        rpcpassword: initialConfig.password || '',
        rpcport: initialConfig.port || '9766',
        rpcallowip: '127.0.0.1',
        server: '1',
        rpcbind: '127.0.0.1',
        accessMethod: 'local', // local, portforward, ngrok, vpn
        ngrokToken: '',
        ngrokCommand: '',
        portForwardPort: '9766',
        ...initialConfig
    });
    const [testing, setTesting] = useState(false);
    const [testResult, setTestResult] = useState(null);

    const totalSteps = 5;

    const generateRodConf = () => {
        let conf = `# ROD Core Configuration File
# Generated by ROD Wallet Setup Wizard

# Enable RPC server
server=${config.server}

# RPC credentials
rpcuser=${config.rpcuser}
rpcpassword=${config.rpcpassword}

# RPC port
rpcport=${config.rpcport}

# RPC bind address
rpcbind=${config.rpcbind}

# Allow RPC connections from
rpcallowip=${config.rpcallowip}

# Optional: Additional settings
# txindex=1
# daemon=1
# maxconnections=50
`;
        return conf;
    };

    const downloadRodConf = () => {
        const content = generateRodConf();
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'rod.conf';
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        a.remove();
        toast.success('rod.conf downloaded');
    };

    const copyRodConf = () => {
        navigator.clipboard.writeText(generateRodConf());
        toast.success('Configuration copied to clipboard');
    };

    const testConnection = async () => {
        setTesting(true);
        setTestResult(null);
        try {
            const response = await base44.functions.invoke('executeRPCCommand', {
                method: 'getblockcount',
                params: []
            });

            if (response.data.success !== false) {
                setTestResult({ success: true, message: 'Connection successful!' });
                toast.success('Connection test passed');
            } else {
                setTestResult({ success: false, message: response.data.error || 'Connection failed' });
            }
        } catch (err) {
            setTestResult({ success: false, message: err.message });
        } finally {
            setTesting(false);
        }
    };

    const handleNext = () => {
        if (step < totalSteps) setStep(step + 1);
    };

    const handleBack = () => {
        if (step > 1) setStep(step - 1);
    };

    const handleComplete = async () => {
        if (onComplete) {
            onComplete(config);
        }
        toast.success('Setup wizard completed!');
    };

    const generateNgrokCommand = () => {
        return `ngrok tcp ${config.rpcport}`;
    };

    return (
        <div className="max-w-4xl mx-auto">
            {/* Progress Bar */}
            <div className="mb-8">
                <div className="flex items-center justify-between mb-2">
                    <span className="text-sm text-slate-400">Step {step} of {totalSteps}</span>
                    <span className="text-sm text-slate-400">{Math.round((step / totalSteps) * 100)}% Complete</span>
                </div>
                <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div 
                        className="h-full bg-gradient-to-r from-purple-500 to-blue-500 transition-all duration-500"
                        style={{ width: `${(step / totalSteps) * 100}%` }}
                    />
                </div>
            </div>

            <Card className="bg-slate-900/80 border-slate-700/50">
                <CardContent className="p-8">
                    {/* Step 1: Welcome */}
                    {step === 1 && (
                        <div className="space-y-6">
                            <div className="text-center space-y-3">
                                <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-blue-500 rounded-full mx-auto flex items-center justify-center">
                                    <Server className="w-8 h-8 text-white" />
                                </div>
                                <h2 className="text-2xl font-bold text-white">Welcome to ROD Core Setup Wizard</h2>
                                <p className="text-slate-400 max-w-2xl mx-auto">
                                    This wizard will guide you through configuring your ROD Core node and RPC settings. 
                                    We'll help you set up secure remote access and test your connection.
                                </p>
                            </div>

                            <div className="grid md:grid-cols-3 gap-4 mt-8">
                                <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                    <Terminal className="w-8 h-8 text-purple-400 mb-2" />
                                    <h3 className="text-white font-semibold mb-1">Configure rod.conf</h3>
                                    <p className="text-sm text-slate-400">Set up RPC credentials and network settings</p>
                                </div>
                                <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                    <Network className="w-8 h-8 text-blue-400 mb-2" />
                                    <h3 className="text-white font-semibold mb-1">Remote Access</h3>
                                    <p className="text-sm text-slate-400">Choose your connection method</p>
                                </div>
                                <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                    <CheckCircle2 className="w-8 h-8 text-green-400 mb-2" />
                                    <h3 className="text-white font-semibold mb-1">Test & Connect</h3>
                                    <p className="text-sm text-slate-400">Verify your configuration works</p>
                                </div>
                            </div>

                            <Alert className="bg-blue-500/10 border-blue-500/30">
                                <Info className="w-4 h-4 text-blue-400" />
                                <AlertDescription className="text-blue-300">
                                    <strong>Prerequisites:</strong> You should have ROD Core installed and running on your computer. 
                                    If not, download it from the official ROD website first.
                                </AlertDescription>
                            </Alert>
                        </div>
                    )}

                    {/* Step 2: Configure rod.conf */}
                    {step === 2 && (
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-2">Configure rod.conf Settings</h2>
                                <p className="text-slate-400">Set up your RPC credentials and basic configuration</p>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <Label className="text-slate-300">RPC Username</Label>
                                    <Input
                                        value={config.rpcuser}
                                        onChange={(e) => setConfig({ ...config, rpcuser: e.target.value })}
                                        placeholder="e.g., roduser"
                                        className="bg-slate-950/50 border-slate-700 text-white"
                                    />
                                    <p className="text-xs text-slate-500 mt-1">Choose a username for RPC authentication</p>
                                </div>

                                <div>
                                    <Label className="text-slate-300">RPC Password</Label>
                                    <Input
                                        type="password"
                                        value={config.rpcpassword}
                                        onChange={(e) => setConfig({ ...config, rpcpassword: e.target.value })}
                                        placeholder="Enter a strong password"
                                        className="bg-slate-950/50 border-slate-700 text-white"
                                    />
                                    <p className="text-xs text-slate-500 mt-1">Use a strong, unique password</p>
                                </div>

                                <div className="grid md:grid-cols-2 gap-4">
                                    <div>
                                        <Label className="text-slate-300">RPC Port</Label>
                                        <Input
                                            value={config.rpcport}
                                            onChange={(e) => setConfig({ ...config, rpcport: e.target.value })}
                                            placeholder="9766"
                                            className="bg-slate-950/50 border-slate-700 text-white"
                                        />
                                        <p className="text-xs text-slate-500 mt-1">Default: 9766</p>
                                    </div>

                                    <div>
                                        <Label className="text-slate-300">RPC Bind Address</Label>
                                        <Input
                                            value={config.rpcbind}
                                            onChange={(e) => setConfig({ ...config, rpcbind: e.target.value })}
                                            placeholder="127.0.0.1"
                                            className="bg-slate-950/50 border-slate-700 text-white"
                                        />
                                        <p className="text-xs text-slate-500 mt-1">Default: 127.0.0.1 (local only)</p>
                                    </div>
                                </div>

                                <div>
                                    <Label className="text-slate-300">RPC Allow IP</Label>
                                    <Input
                                        value={config.rpcallowip}
                                        onChange={(e) => setConfig({ ...config, rpcallowip: e.target.value })}
                                        placeholder="127.0.0.1"
                                        className="bg-slate-950/50 border-slate-700 text-white"
                                    />
                                    <p className="text-xs text-slate-500 mt-1">
                                        Use 127.0.0.1 for local only, or 0.0.0.0/0 to allow all (not recommended)
                                    </p>
                                </div>
                            </div>

                            <Alert className="bg-amber-500/10 border-amber-500/30">
                                <AlertTriangle className="w-4 h-4 text-amber-400" />
                                <AlertDescription className="text-amber-300">
                                    <strong>Security Note:</strong> Keep your RPC credentials secure. Never share them publicly 
                                    or commit them to version control.
                                </AlertDescription>
                            </Alert>
                        </div>
                    )}

                    {/* Step 3: Choose Access Method */}
                    {step === 3 && (
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-2">Choose Remote Access Method</h2>
                                <p className="text-slate-400">How do you want to connect to your ROD Core node?</p>
                            </div>

                            <Tabs value={config.accessMethod} onValueChange={(value) => setConfig({ ...config, accessMethod: value })}>
                                <TabsList className="grid grid-cols-4 bg-slate-800">
                                    <TabsTrigger value="local">Local Only</TabsTrigger>
                                    <TabsTrigger value="ngrok">ngrok (Easy)</TabsTrigger>
                                    <TabsTrigger value="portforward">Port Forward</TabsTrigger>
                                    <TabsTrigger value="vpn">VPN</TabsTrigger>
                                </TabsList>

                                <TabsContent value="local" className="space-y-4">
                                    <div className="p-6 bg-slate-800/50 rounded-lg border border-slate-700">
                                        <div className="flex items-start gap-3 mb-4">
                                            <Server className="w-6 h-6 text-green-400 flex-shrink-0 mt-1" />
                                            <div>
                                                <h3 className="text-white font-semibold mb-2">Local Connection Only</h3>
                                                <p className="text-slate-400 text-sm mb-3">
                                                    Connect only from the same computer where ROD Core is running. 
                                                    Most secure option but no remote access.
                                                </p>
                                                <div className="space-y-2">
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Most secure</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">No configuration needed</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <AlertTriangle className="w-4 h-4 text-amber-400" />
                                                        <span className="text-sm text-slate-300">No remote access</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </TabsContent>

                                <TabsContent value="ngrok" className="space-y-4">
                                    <div className="p-6 bg-slate-800/50 rounded-lg border border-purple-500/30">
                                        <div className="flex items-start gap-3 mb-4">
                                            <Zap className="w-6 h-6 text-purple-400 flex-shrink-0 mt-1" />
                                            <div>
                                                <h3 className="text-white font-semibold mb-2">ngrok Tunnel (Recommended)</h3>
                                                <p className="text-slate-400 text-sm mb-3">
                                                    Easiest way to access your node remotely. Creates a secure tunnel without 
                                                    router configuration.
                                                </p>
                                                <div className="space-y-2">
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Easy setup (5 minutes)</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">No router configuration</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Secure tunnel with HTTPS</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <Info className="w-4 h-4 text-blue-400" />
                                                        <span className="text-sm text-slate-300">Free tier available</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <Badge className="bg-purple-500/20 text-purple-300">Recommended for Beginners</Badge>
                                    </div>
                                </TabsContent>

                                <TabsContent value="portforward" className="space-y-4">
                                    <div className="p-6 bg-slate-800/50 rounded-lg border border-slate-700">
                                        <div className="flex items-start gap-3 mb-4">
                                            <Network className="w-6 h-6 text-blue-400 flex-shrink-0 mt-1" />
                                            <div>
                                                <h3 className="text-white font-semibold mb-2">Port Forwarding</h3>
                                                <p className="text-slate-400 text-sm mb-3">
                                                    Configure your router to forward traffic to your node. More control but 
                                                    requires router access.
                                                </p>
                                                <div className="space-y-2">
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Direct connection</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">No third-party service</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <AlertTriangle className="w-4 h-4 text-amber-400" />
                                                        <span className="text-sm text-slate-300">Requires router configuration</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <AlertTriangle className="w-4 h-4 text-amber-400" />
                                                        <span className="text-sm text-slate-300">Exposes your home IP</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </TabsContent>

                                <TabsContent value="vpn" className="space-y-4">
                                    <div className="p-6 bg-slate-800/50 rounded-lg border border-slate-700">
                                        <div className="flex items-start gap-3 mb-4">
                                            <Shield className="w-6 h-6 text-cyan-400 flex-shrink-0 mt-1" />
                                            <div>
                                                <h3 className="text-white font-semibold mb-2">VPN Connection</h3>
                                                <p className="text-slate-400 text-sm mb-3">
                                                    Use a VPN (like Tailscale or WireGuard) to securely access your node. 
                                                    Most secure for remote access.
                                                </p>
                                                <div className="space-y-2">
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Most secure</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <CheckCircle2 className="w-4 h-4 text-green-400" />
                                                        <span className="text-sm text-slate-300">Private network</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <AlertTriangle className="w-4 h-4 text-amber-400" />
                                                        <span className="text-sm text-slate-300">Requires VPN setup</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <Info className="w-4 h-4 text-blue-400" />
                                                        <span className="text-sm text-slate-300">Tailscale recommended</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <Badge className="bg-cyan-500/20 text-cyan-300">Most Secure</Badge>
                                    </div>
                                </TabsContent>
                            </Tabs>
                        </div>
                    )}

                    {/* Step 4: Setup Instructions */}
                    {step === 4 && (
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-2">
                                    {config.accessMethod === 'ngrok' && 'ngrok Setup Instructions'}
                                    {config.accessMethod === 'portforward' && 'Port Forwarding Instructions'}
                                    {config.accessMethod === 'vpn' && 'VPN Setup Instructions'}
                                    {config.accessMethod === 'local' && 'Download rod.conf File'}
                                </h2>
                                <p className="text-slate-400">Follow these steps to complete your setup</p>
                            </div>

                            {config.accessMethod === 'ngrok' && (
                                <div className="space-y-4">
                                    <Alert className="bg-purple-500/10 border-purple-500/30">
                                        <Zap className="w-4 h-4 text-purple-400" />
                                        <AlertDescription className="text-purple-300">
                                            <strong>Quick Setup:</strong> Follow these 3 simple steps to connect via ngrok
                                        </AlertDescription>
                                    </Alert>

                                    <div className="space-y-4">
                                        <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                            <div className="flex items-start gap-3 mb-3">
                                                <div className="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center flex-shrink-0 text-white font-bold">1</div>
                                                <div className="flex-1">
                                                    <h3 className="text-white font-semibold mb-2">Install ngrok</h3>
                                                    <p className="text-slate-400 text-sm mb-3">
                                                        Download and install ngrok from their official website
                                                    </p>
                                                    <Button
                                                        variant="outline"
                                                        size="sm"
                                                        onClick={() => window.open('https://ngrok.com/download', '_blank')}
                                                        className="text-purple-400 border-purple-500/50">
                                                        Download ngrok
                                                    </Button>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                            <div className="flex items-start gap-3 mb-3">
                                                <div className="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center flex-shrink-0 text-white font-bold">2</div>
                                                <div className="flex-1">
                                                    <h3 className="text-white font-semibold mb-2">Run ngrok</h3>
                                                    <p className="text-slate-400 text-sm mb-3">
                                                        Open terminal/command prompt and run this command:
                                                    </p>
                                                    <div className="bg-slate-950 rounded-lg p-3 font-mono text-sm text-green-400 flex items-center justify-between">
                                                        <code>{generateNgrokCommand()}</code>
                                                        <Button
                                                            variant="ghost"
                                                            size="icon"
                                                            onClick={() => {
                                                                navigator.clipboard.writeText(generateNgrokCommand());
                                                                toast.success('Command copied');
                                                            }}
                                                            className="h-6 w-6 text-slate-400 hover:text-white">
                                                            <Copy className="w-3 h-3" />
                                                        </Button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                            <div className="flex items-start gap-3 mb-3">
                                                <div className="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center flex-shrink-0 text-white font-bold">3</div>
                                                <div className="flex-1">
                                                    <h3 className="text-white font-semibold mb-2">Get Your ngrok URL</h3>
                                                    <p className="text-slate-400 text-sm mb-3">
                                                        After running ngrok, it will display a forwarding URL like:
                                                        <code className="block mt-2 bg-slate-950 p-2 rounded text-green-400 text-xs">
                                                            tcp://0.tcp.ngrok.io:12345 -&gt; localhost:{config.rpcport}
                                                        </code>
                                                    </p>
                                                    <p className="text-slate-400 text-sm">
                                                        Use this URL when configuring your RPC connection in the Admin panel.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <Alert className="bg-blue-500/10 border-blue-500/30">
                                        <Info className="w-4 h-4 text-blue-400" />
                                        <AlertDescription className="text-blue-300">
                                            <strong>Note:</strong> Keep the ngrok terminal window open while using the wallet. 
                                            The tunnel will close when you close the terminal.
                                        </AlertDescription>
                                    </Alert>
                                </div>
                            )}

                            {config.accessMethod === 'portforward' && (
                                <div className="space-y-4">
                                    <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                        <h3 className="text-white font-semibold mb-3">Port Forwarding Steps:</h3>
                                        <ol className="space-y-3 text-slate-400 text-sm list-decimal list-inside">
                                            <li>Log into your router's admin panel (usually 192.168.1.1 or 192.168.0.1)</li>
                                            <li>Find the Port Forwarding section (may be under Advanced Settings)</li>
                                            <li>Create a new port forward rule:
                                                <ul className="ml-6 mt-2 space-y-1">
                                                    <li>• External Port: {config.rpcport}</li>
                                                    <li>• Internal Port: {config.rpcport}</li>
                                                    <li>• Internal IP: Your computer's local IP</li>
                                                    <li>• Protocol: TCP</li>
                                                </ul>
                                            </li>
                                            <li>Find your public IP at <a href="https://whatismyipaddress.com" target="_blank" className="text-purple-400 hover:underline">whatismyipaddress.com</a></li>
                                            <li>Use your public IP and port {config.rpcport} in the RPC configuration</li>
                                        </ol>
                                    </div>

                                    <Alert className="bg-amber-500/10 border-amber-500/30">
                                        <AlertTriangle className="w-4 h-4 text-amber-400" />
                                        <AlertDescription className="text-amber-300">
                                            <strong>Security Warning:</strong> Port forwarding exposes your node to the internet. 
                                            Use strong credentials and consider IP whitelisting.
                                        </AlertDescription>
                                    </Alert>
                                </div>
                            )}

                            {config.accessMethod === 'vpn' && (
                                <div className="space-y-4">
                                    <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                        <h3 className="text-white font-semibold mb-3">Recommended VPN: Tailscale</h3>
                                        <ol className="space-y-3 text-slate-400 text-sm list-decimal list-inside">
                                            <li>Install Tailscale on both your node computer and the device you'll access from</li>
                                            <li>Sign in with the same account on both devices</li>
                                            <li>They will automatically connect via a secure private network</li>
                                            <li>Use the Tailscale IP address in your RPC configuration</li>
                                        </ol>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            onClick={() => window.open('https://tailscale.com/download', '_blank')}
                                            className="mt-4 text-cyan-400 border-cyan-500/50">
                                            Download Tailscale
                                        </Button>
                                    </div>
                                </div>
                            )}

                            <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-700">
                                <h3 className="text-white font-semibold mb-3">Your rod.conf Configuration:</h3>
                                <Textarea
                                    value={generateRodConf()}
                                    readOnly
                                    rows={12}
                                    className="bg-slate-950 border-slate-700 text-green-400 font-mono text-xs mb-3"
                                />
                                <div className="flex gap-2">
                                    <Button
                                        onClick={downloadRodConf}
                                        className="bg-purple-600 hover:bg-purple-700">
                                        <Download className="w-4 h-4 mr-2" />
                                        Download rod.conf
                                    </Button>
                                    <Button
                                        variant="outline"
                                        onClick={copyRodConf}
                                        className="border-slate-600">
                                        <Copy className="w-4 h-4 mr-2" />
                                        Copy to Clipboard
                                    </Button>
                                </div>
                                <p className="text-xs text-slate-500 mt-3">
                                    Save this file to your ROD Core data directory. On Windows: %APPDATA%\Rod | On Mac: ~/Library/Application Support/Rod | On Linux: ~/.rod
                                </p>
                            </div>
                        </div>
                    )}

                    {/* Step 5: Test Connection */}
                    {step === 5 && (
                        <div className="space-y-6">
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-2">Test Your Connection</h2>
                                <p className="text-slate-400">Let's verify that everything is configured correctly</p>
                            </div>

                            <Alert className="bg-blue-500/10 border-blue-500/30">
                                <Info className="w-4 h-4 text-blue-400" />
                                <AlertDescription className="text-blue-300">
                                    Make sure ROD Core is running and configured with the settings from this wizard before testing.
                                </AlertDescription>
                            </Alert>

                            <div className="p-6 bg-slate-800/50 rounded-lg border border-slate-700 text-center">
                                {!testResult && (
                                    <div className="space-y-4">
                                        <Server className="w-16 h-16 text-slate-600 mx-auto" />
                                        <p className="text-slate-400">Ready to test your RPC connection</p>
                                        <Button
                                            onClick={testConnection}
                                            disabled={testing}
                                            className="bg-purple-600 hover:bg-purple-700">
                                            {testing ? (
                                                <>
                                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                                    Testing Connection...
                                                </>
                                            ) : (
                                                <>
                                                    <Zap className="w-4 h-4 mr-2" />
                                                    Test Connection
                                                </>
                                            )}
                                        </Button>
                                    </div>
                                )}

                                {testResult && testResult.success && (
                                    <div className="space-y-4">
                                        <CheckCircle2 className="w-16 h-16 text-green-400 mx-auto" />
                                        <h3 className="text-xl font-semibold text-white">Connection Successful!</h3>
                                        <p className="text-slate-400">{testResult.message}</p>
                                        <Button
                                            onClick={testConnection}
                                            variant="outline"
                                            size="sm"
                                            className="border-slate-600">
                                            Test Again
                                        </Button>
                                    </div>
                                )}

                                {testResult && !testResult.success && (
                                    <div className="space-y-4">
                                        <AlertTriangle className="w-16 h-16 text-red-400 mx-auto" />
                                        <h3 className="text-xl font-semibold text-white">Connection Failed</h3>
                                        <p className="text-slate-400">{testResult.message}</p>
                                        <div className="space-y-2 text-left bg-slate-950/50 rounded-lg p-4">
                                            <p className="text-sm text-slate-300 font-semibold">Troubleshooting:</p>
                                            <ul className="text-sm text-slate-400 space-y-1">
                                                <li>• Ensure ROD Core is running</li>
                                                <li>• Verify rod.conf is in the correct directory</li>
                                                <li>• Restart ROD Core after changing configuration</li>
                                                <li>• Check that credentials match</li>
                                                <li>• If using ngrok, ensure the tunnel is active</li>
                                            </ul>
                                        </div>
                                        <Button
                                            onClick={testConnection}
                                            className="bg-purple-600 hover:bg-purple-700">
                                            <Zap className="w-4 h-4 mr-2" />
                                            Retry Test
                                        </Button>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Navigation Buttons */}
                    <div className="flex justify-between mt-8 pt-6 border-t border-slate-700">
                        <Button
                            onClick={handleBack}
                            disabled={step === 1}
                            variant="outline"
                            className="border-slate-600">
                            <ArrowLeft className="w-4 h-4 mr-2" />
                            Back
                        </Button>

                        {step < totalSteps ? (
                            <Button
                                onClick={handleNext}
                                className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
                                Next
                                <ArrowRight className="w-4 h-4 ml-2" />
                            </Button>
                        ) : (
                            <Button
                                onClick={handleComplete}
                                disabled={!testResult || !testResult.success}
                                className="bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700">
                                <CheckCircle2 className="w-4 h-4 mr-2" />
                                Complete Setup
                            </Button>
                        )}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}